[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/votar/*"
  to = "/.netlify/functions/votar/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/votar"
  to = "/.netlify/functions/votar"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
